### ISSUE TITLE
create developer, design role descriptions

### ISSUE THREAD

**Issue by sandyklc** [ubclaunchpad/docs#108]
https://docs.ubclaunchpad.com/handbook/#recruitment

Hopefully finish these by Mid-July?

**Comment by bobheadxi** [comment]
Note to self: update roles in https://sourcegraph.com/github.com/ubclaunchpad/ubclaunchpad.com/-/blob/src/config.ts#L43-73 when we have these descriptions ready

**Comment by bobheadxi** [comment]
removed strategy since as per https://ubclaunchpad.slack.com/archives/G013BC5RC22/p1592021316028000?thread_ts=1592020822.021900&cid=G013BC5RC22 we're unlikely to be recruiting for strategy this fall

**Comment by renehuang1999** [comment]
developers draft - https://docs.google.com/document/d/1beIX7ujol4gcySnzGlaE3Admj2CgP5x_CQ-m_O5dk-4/edit
designers draft - https://docs.google.com/document/d/1wPbzR9XBX4KfLHE4z4VnXxqL8KjFMXymwYqLOwpqju4/edit
