### ISSUE TITLE
document our social media accounts and how best to use them

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/docs#109]
I'll get a page set up for this with a list and some ideas and @sandyklc you can follow up and flesh it out? :)

**Comment by bobheadxi** [comment]
I'll probably set this up under `/handbook/tools/social-media.md`

**Comment by sandyklc** [comment]
Yup that sounds awesome!

**Comment by bobheadxi** [comment]
@sandyklc handing this off to you now! :)

**Comment by sandyklc** [comment]
Will be working on this with @andrewzulaybar !

**Comment by bobheadxi** [comment]
@sandyklc will you be adding more to #137 or making a new PR? (not sure if I should merge that first and let you add changes, or leave it up for comments from you and @andrewzulaybar)

**Comment by sandyklc** [comment]
We'll be adding in the TODOs in the [docs](https://docs.ubclaunchpad.com/handbook/tools/social-media)

**Comment by bobheadxi** [comment]
> We'll be adding in the TODOs in the docs

#137 revamps that page already, so the TODOs are no longer valid :)

**Comment by sandyklc** [comment]
Okay sounds good!
