### ISSUE TITLE
document Sync stack

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/docs#128]
follow-up to #123 

https://docs.google.com/document/d/1ZyX8MtEF7v_ka6EvxtyrTnYZv_0YCwVAyygOQmzARYY/edit

also cc @srijonsaha

**Comment by srijonsaha** [comment]
I can help out with this since I did a lot of the decision making on the stack.

**Comment by bobheadxi** [comment]
@srijonsaha that would be great! You should ask @johnagl to loop you in :) It should follow the format in #123, but I'm open to suggestions on how to best document these
