### ISSUE TITLE
document per-term tasks

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/docs#150]
Probably things like handoff, leads selection (https://github.com/ubclaunchpad/docs/issues/146), and club objectives retrospectives (https://github.com/ubclaunchpad/docs/pull/149#discussion_r462022655)

**Comment by renehuang1999** [comment]
just a thought on objective assessment - maybe we can have a small check-in on the objectives once per month, just to make sure we're on the right track? we could also have a mid-point assessment in december where we ask members questions that reflect our objectives (e.g. on a scale 1-5 how often do you collaborate with someone on a different role?)

**Comment by bobheadxi** [comment]
> mid-point assessment in december

sounds like a good idea!
