### ISSUE TITLE
Applicant having trouble accessing all files and Slack

### ISSUE THREAD

**Issue by Zhuoxi-Han** [ubclaunchpad/docs#169]
Hi, 
I'm trying to join the design team but I do not know where to start. I do not have acccess to the files listed on the website page and I cannot login to Slack because my email address does not match the domain required, as shown in the screenshot attached.
<img width="746" alt="Screen Shot 2020-09-14 at 3 24 10 PM" src="https://user-images.githubusercontent.com/68973193/93144217-5d5f1700-f69e-11ea-94a4-5cf81b308875.png">

**Comment by bobheadxi** [comment]
Hey,

To have access to our Drive or our Slack, you will have to have gone through our [recruitment process](https://docs.ubclaunchpad.com/handbook/recruitment/overview) and been extended an offer to join. If you have already applied and interviewed, we will be sending out design decisions in the next few days - if not, please [subscribe to our newsletter](ubclaunchpad.com/newsletter) to get updated when we open for applications again.
