### ISSUE TITLE
bug: opening links in new tab from homepage shows HTML

### ISSUE THREAD

**Issue by engineereng** [ubclaunchpad/docs#180]
Description:

Opening the following links from https://docs.ubclaunchpad.com/ in a different browser tab results in the viewer seeing the raw HTML:

- the link to https://docs.ubclaunchpad.com/introduction.html (under the "Get started" button)
- the link to https://docs.ubclaunchpad.com/CONTRIBUTING.html (under "Spot something off? Want to add some content? Take a look at our contribution guide!")

Found on Google Chrome Version 85.0.4183.121 (Official Build) (64-bit).

Steps to replicate this issue:

1. Right click either of the links mentioned above and select new tab

![right click](https://user-images.githubusercontent.com/38707101/94393544-2104cf80-0110-11eb-9844-e821199e88a5.jpg)

2. Click "new tab". The page will redirect to the .HTML file.
![new tab](https://user-images.githubusercontent.com/38707101/94393551-2530ed00-0110-11eb-9e7b-b35868b8ce8e.jpg)

Recommended fixes:
Link to https://docs.ubclaunchpad.com/introduction instead of https://docs.ubclaunchpad.com/introduction.html and https://docs.ubclaunchpad.com/CONTRIBUTING instead of https://docs.ubclaunchpad.com/CONTRIBUTING.html

**Comment by bobheadxi** [comment]
Unfortunately, this might be a VuePress limitation, since in markdown we link directly to markdown files and  - though I swear we have a plugin to drop the trailing `.html` extension:

https://github.com/ubclaunchpad/docs/blob/master/.vuepress/config.js#L137-L138

**Comment by bobheadxi** [comment]
I managed to include a fix for this in #197
