### ISSUE TITLE
Inconsistent capitalization of "leadership", "strategy", "developer

### ISSUE THREAD

**Issue by engineereng** [ubclaunchpad/docs#193]
While this isn't as big of a deal for the developer and design roles, we seem to be inconsistent in how we capitalize the terms for our roles and teams, especially "strategy" and "design".

I suggest we use terms such as "the Strategy team" and "the Design team" as they are names and titles of teams.

**Comment by bobheadxi** [comment]
Thanks! I added some guidelines based on this in https://github.com/ubclaunchpad/docs/pull/195
