### ISSUE TITLE
Add links to non-code LP repos

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/docs#25]
Things like:
- ubclaunchpad/tech-leads
- ubclaunchpad/strategy
- ubclaunchpad/design
- ubclaunchpad/exec
- ubclaunchpad/humans

**Comment by rwblickhan** [comment]
How do you propose including this? As a section in the README? Or a whole new document that just lists "important repos"?

**Comment by bobheadxi** [comment]
It might be good to feature them in the README, as many also serve as documentation repos of their own (perhaps not yet, but ideally they'll become hubs of information about their respective teams)

**Comment by rwblickhan** [comment]
`ubclaunchpad/humans` seems to be unused; I won't include it.

**Comment by rwblickhan** [comment]
Seeing as how `ubclaunchpad/exec` is only open to (I believe?) three people, I also won't include it; it doesn't seem generally useful.
