### ISSUE TITLE
design onboarding + workflows

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/docs#89]
https://docs.ubclaunchpad.com/handbook/onboarding/design

probably structure similarly to https://docs.ubclaunchpad.com/handbook/onboarding/leads

**Comment by sandyklc** [comment]
Made some updates to the Design onboarding page! Let me know what you think!

**Comment by bobheadxi** [comment]
Thanks! I've left a review - also, heads up that you can "connect" issues/PRs by writing their number:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/23356519/83042463-8af05980-9ff6-11ea-90f8-38d4b24380e2.png">

now it shows up everywhere:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/23356519/83042511-9479c180-9ff6-11ea-84e5-3bd90376c17c.png">

**Comment by sandyklc** [comment]
Ohhh gotcha, thank you for letting me know about that! That's super useful!
