### ISSUE TITLE
refresh project management

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/docs#98]
https://docs.ubclaunchpad.com/handbook/project-management/repositories

* [x] repository documentation
* [ ] CI/CD
   * [ ] platforms
   * [ ] continuous integration - enforcing standards, tests
   * [ ] continuous deployment - links to tools

**Comment by achinth-b** [comment]
I've got this! Will work on it tonight

**Comment by bobheadxi** [comment]
The only section left is the CI/CD stuff, I can take care of that
